# Generated by Django 3.1.2 on 2020-10-28 23:39

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='HostingOrganizationApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMMUNE', 'Commune'), ('DEPARTEMENT', 'Département'), ('REGION', 'Région'), ('EPCI', 'EPCI'), ('COLLECTIVITE', 'Collectivité'), ('PRIVATE', 'Entreprise privée')], max_length=20)),
                ('has_candidate', models.BooleanField()),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_position', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_looking', models.BooleanField()),
                ('situation_job', models.BooleanField()),
                ('situation_learning', models.BooleanField()),
                ('situation_graduated', models.BooleanField()),
                ('formation', models.CharField(blank=True, max_length=200)),
                ('has_experience', models.BooleanField()),
                ('zip_code', models.CharField(max_length=10)),
                ('max_distance', models.IntegerField()),
                ('start_date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.coachapplication')),
            ],
        ),
    ]
