# Generated by Django 3.1.2 on 2020-10-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_coachapplication_hostingorganizationapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostingorganizationapplication',
            old_name='contact_position',
            new_name='contact_job',
        ),
    ]
