# Generated by Django 3.1.2 on 2020-10-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_auto_20201029_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachApplication',
            new_name='Coach',
        ),
        migrations.RenameModel(
            old_name='HostingOrganizationApplication',
            new_name='HostOrganization',
        ),
    ]
