# Generated by Django 3.1.2 on 2020-10-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_auto_20201029_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', related_query_name='matchings', to='djapp.coach')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', related_query_name='matchings', to='djapp.hostorganization')),
            ],
        ),
    ]
