# Generated by Django 3.1.3 on 2020-11-24 18:21

from django.db import migrations, models
import djapp.models


def gen_key(apps, schema_editor):
    Coach = apps.get_model('djapp', 'Coach')
    for m in Coach.objects.all():
        m.email_confirmation_key = djapp.models.random_key_50()
        m.save(update_fields=['email_confirmation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_auto_20201030_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='parent',
        ),
        migrations.AddField(
            model_name='coach',
            name='email_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='email_confirmation_key',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(gen_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coach',
            name='email_confirmation_key',
            field=models.CharField(default=djapp.models.random_key_50, max_length=50, unique=True),
        ),
    ]
