# Generated by Django 3.1.3 on 2020-11-26 22:47

from django.db import migrations
from django.utils import timezone


def validate_emails(apps, schema_editor):
    Coach = apps.get_model('djapp', 'Coach')
    Coach.objects.all().update(email_confirmed=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0008_coach_blocked'),
    ]

    operations = [
        migrations.RunPython(validate_emails, migrations.RunPython.noop),
    ]
