# Generated by Django 3.1.3 on 2020-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('djapp', '0010_auto_20201130_1154'), ('djapp', '0011_auto_20201130_1743')]

    dependencies = [
        ('djapp', '0009_validate_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='commune_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='departement_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='geo_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='region_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='commune_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='departement_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='geo_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='region_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
