# Generated by Django 3.1.3 on 2020-12-01 16:04

from django.db import migrations, models
import djapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0010_auto_20201130_1154_squashed_0011_auto_20201130_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostorganization',
            name='blocked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='email_confirmation_key',
            field=models.CharField(default=djapp.models.random_key_50, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='email_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='validated',
            field=models.DateTimeField(null=True),
        ),
    ]
