# Generated by Django 3.1.3 on 2020-12-01 16:04

from django.db import migrations, models
import djapp.models


def gen_key(apps, schema_editor):
    HostOrganization = apps.get_model('djapp', 'HostOrganization')
    for m in HostOrganization.objects.all():
        m.email_confirmation_key = djapp.models.random_key_50()
        m.save(update_fields=['email_confirmation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0010_auto_20201130_1154_squashed_0011_auto_20201130_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostorganization',
            name='blocked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='email_confirmation_key',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='email_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='validated',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(gen_key, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hostorganization',
            name='email_confirmation_key',
            field=models.CharField(default=djapp.models.random_key_50, max_length=50, unique=True),
        ),
    ]
