# Generated by Django 3.1.3 on 2020-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0012_validate_emails_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='unsubscribe_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='coach',
            name='unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='unsubscribe_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostorganization',
            name='blocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostorganization',
            name='validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
