# Generated by Django 3.1.3 on 2020-12-07 13:37

from django.db import migrations, models
from django.db.models import F


def copy_states(apps, schema_editor):
    Matching = apps.get_model('djapp', 'Matching')
    for matching in Matching.objects.all():
        if matching.coach_accepted or matching.coach_rejected:
            if date_more_recent(matching.coach_accepted, matching.coach_rejected):
                matching.coach_contact_ok = True
                matching.coach_contact_datetime = matching.coach_accepted
            else:
                matching.coach_contact_ok = False
                matching.coach_contact_datetime = matching.coach_rejected

        if matching.host_accepted or matching.host_rejected:
            if date_more_recent(matching.host_accepted, matching.host_rejected):
                matching.host_contact_ok = True
                matching.host_contact_datetime = matching.host_accepted
            else:
                matching.host_contact_ok = False
                matching.host_contact_datetime = matching.host_rejected

        matching.save()


def copy_states_reverse(apps, schema_editor):
    Matching = apps.get_model('djapp', 'Matching')
    Matching.objects.filter(coach_contact_ok=True).update(coach_accepted=F('coach_contact_datetime'))
    Matching.objects.filter(coach_contact_ok=False).update(coach_rejected=F('coach_contact_datetime'))
    Matching.objects.filter(host_contact_ok=True).update(host_accepted=F('host_contact_datetime'))
    Matching.objects.filter(host_contact_ok=False).update(host_rejected=F('host_contact_datetime'))


def date_more_recent(d1, d2):
    if d1 is None:
        return False
    if d2 is None:
        return True
    else:
        return d1 <= d2


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0013_auto_20201203_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='coach_contact_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='coach_contact_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='host_contact_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='host_contact_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='host_interview_result_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='host_interview_result_ok',
            field=models.BooleanField(blank=True, null=True),
        ),

        migrations.RunPython(copy_states, copy_states_reverse),

        migrations.RenameField(
            model_name='matching',
            old_name='coach_accepted',
            new_name='old_coach_accepted',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='coach_rejected',
            new_name='old_coach_rejected',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='host_accepted',
            new_name='old_host_accepted',
        ),
        migrations.RenameField(
            model_name='matching',
            old_name='host_rejected',
            new_name='old_host_rejected',
        ),
    ]
