# Generated by Django 3.1.3 on 2020-12-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0014_auto_20201207_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='host_meeting_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='host_meeting_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
