# Generated by Django 3.1.5 on 2021-01-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0016_hostorganization_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostorganization',
            name='coaches_requested',
            field=models.IntegerField(null=True),
        ),
    ]
