# Generated by Django 3.1.3 on 2021-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0017_hostorganization_coaches_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='disponible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
