# Generated by Django 3.1.5 on 2021-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0018_coach_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
