# Generated by Django 3.1.5 on 2021-08-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0019_auto_20210126_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='com_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='com_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostorganization',
            name='type',
            field=models.CharField(choices=[('COMMUNE', 'Commune'), ('DEPARTEMENT', 'Département'), ('REGION', 'Région'), ('EPCI', 'EPCI'), ('COLLECTIVITE', 'Collectivité'), ('GIP', 'GIP'), ('PRIVATE', 'Entreprise privée')], max_length=20),
        ),
    ]
