# Generated by Django 3.2.19 on 2023-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0020_auto_20210830_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostorganization',
            name='coordinator_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hostorganization',
            name='wants_coordinators',
            field=models.BooleanField(default=False),
        ),
    ]
